- name: install mysql
  hosts: mysql
  become: yes
  tasks: 
  - name: Disable current MySQL version
    ansible.builtin.command: yum module disable mysql -y
  - name: mysql.repo
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo
  - name: install mysql 
    ansible.builtin.yum:
      name: mysql
      state: installed
  - name: restart mysqld
    ansible.builtin.service:
      name: mysqld
      state: restarted
      enabled: true
  - name: setup mysql root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1